### ISSUE TITLE
Error: Cannot find module on lift

### ISSUE THREAD

**Issue by cludden** [mastilver/sails-hook-parametized-policies#2]
Receiving a 'Cannot find module' error on lift. I believe this is due to 'require' being executed in the context of the node_modules/sails-hook-parametrized-policies directory.

I was able to fix by changing index.js#78 from

```
var factory = require(sails.config.paths.policyFactories + '/' + factoryName);
```

to

```
var factory = require(sails.config.appPath + sails.config.paths.policyFactories + '/' + factoryName);
```

Would you be willing to accept a PR with this change?

**Comment by mastilver** [comment]
just released version 0.3.1 to fix this issue
Let me know if you run into any other issues!
