### ISSUE TITLE
Everything is great but Apparently I receive this error

### ISSUE THREAD

**Issue by ericmaro** [mastilver/sails-hook-parametized-policies#4]
`connect deprecated res.headerSent: use standard res.headersSent api\policyFactories\or.js:16:33`

I use sails 0.12.1

**Comment by mastilver** [comment]
I'm not using `sails` anymore
This have been tested using `sails@0.11`, what's your version?

**Comment by mastilver** [comment]
test are passing with `sails@0.12.1`, see #5 

Could you send me a pull request with a failing test

**Comment by mastilver** [comment]
@ericmaro closing this down
Re-open it if it's still an issue
